theme: jekyll-theme-leap-day
title: CoPlayer
description: CoPlayer is a media player based on GStreamer and Qt5.
show_downloads: "true"
github:
  repository_url: https://github.com/coplayer-org/CoPlayer
